[project]
name = "data-sources"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "polars>=1.28.1",
    "pyarrow<19.0.0",
    "snowflake-connector-python>=3.14.1",
]
