[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.6"
hooks = [
  { id = "ruff-check", args = ["--fix", "--select", "I,F401"] },
  { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.11"
hooks = [
  { id = "uv-export", args = ["--no-hashes", "--no-dev", "--output-file=requirements.txt"] },
]

[[repos]]
repo = "https://github.com/kynan/nbstripout"
rev = "0.9.1"
hooks = [
    { id = "nbstripout" },
]
