---
title: VS Code in Posit Workbench Webinar
date: 2024-03-19
author: Sam Edwardes (Solutions Engineer at Posit)
toc: true
---

## About

A webinar for using VS Code in Posit Workbench.

- To see the source code and the example `.py` and `.ipynb` files please refer to this repo: <https://github.com/SamEdwardes/rstudio-demos/tree/main/webinars/2024-03-19_vscode-in-workbench>.
- To see this document rendered on Quarto Pub visit: <https://samedwardes.quarto.pub/vs-code-in-posit-workbench-webinar-2024-03-19/>

## Additional Resources

- VS Code Docs: <https://code.visualstudio.com/Docs>
- Python for VS Code Docs: <https://code.visualstudio.com/Docs>
- Command Palette: <https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette>
- Multiple Cursors: <https://code.visualstudio.com/docs/editor/codebasics>
- Keyboard Shortcuts: <https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference>

## Tasks

**Navigating the File System**

- [ ] Open a folder with the `File` menu.
- [ ] Open a folder with the Command Pallet `>File: Open Folder`.

**Command Pallet**

- [ ] Open the command pallet with `Cmd` + `Shift` + `p`.
- [ ] Open a file with `Cmd` + `p`.
- [ ] Open your home directory, then open this project again.
- [ ] Open the settings with `>Preferences: Open User Settings`.
- [ ] Open the terminal with `>Terminal: Create New Terminal`.

**Understanding workspaces in VS Code vs. Projects in RStudio**

- VS Code does not have a notion of projects.
- You can think of the directory that you choose to open VS Code as the project. VS Code refers to this as the "Workspace"
- Workspace specific settings are stored in the `./vscode/` directory.
- [ ] Change a setting for this Workspace only with `Preferences: Open Workspace Settings`

**Extensions**

- VS Code is a simple text editor. The power comes from extensions!
- Many of the best Python extensions are developed by Microsoft, but anyone can develop and share an extensions.
- Workbench will automatically include the basic Python extensions.
- See `./vscode/extensions.json` for my recommended extensions.

**The terminal**

- [ ] See all of the terminal commands with `>Terminal:`
- [ ] Toggle the bottom pane using `Cmd` + `j`.
- [ ] Toggle the terminal using ^ + `\``

**Working with Python files**

- [ ] Create a virtual environment. (Tip: open VS Code in the same folder as the python .venv, otherwise it can be finnicky with auto-complete)
- [ ] IntelliSense (<https://code.visualstudio.com/docs/editor/intellisense>)
    - Trigger IntelliSense with `^Space`
    - Use arrow keys to select
    - Press `Tab` or `Enter` to insert
- [ ] Quick fix with `Cmd` + `.`
- [ ] RStudio style interactive coding with Python using `Shift` + `Enter`.
- [ ] `#%%` For running chunks of a script, and showing off the interactive window
- [ ] Linting and Formatting with `>Ruff: ...`
- [ ] Debugging
    - [ ] Set a breakpoint
    - [ ] Run with the debugger
- [ ] Refactoring with `F2` or `>Rename Symbol`
- [ ] VS Code Workbench Jobs

**Working with Notebooks**

- Like Jupyter Notebooks, but with all the great IDE features of VS Code like the Command Pallet, intellisense, formatting, git version control, etc.
- [ ] Selecting the kernel - it auto prompts me to install `ipykernel`
- [ ] Variable explorer

**Other tips and tricks**

- [ ] Understanding VS Code settings
    - [ ] User settings
    - [ ] Workspace settings
    - [ ] JSON vs. UI settings
- [ ] How to get back to Workbench home page.
- [ ] Multiple cursors (<https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor>)
    - [ ] Create multiple aligned cursors: `Cmd` + `Shift` + `Up`/`Down`.
    - [ ] Create multiple cursors anywhere: Hold `Option` + `Click`.
    - [ ] Move line or selected text up/down: `Option` + `Up`/`Down`.
    - [ ] Duplicate selected text or line: `Option` + `Shift` + `Up`/`Down`.
    - [ ] Create cursor at all instances of selected text: `Cmd` + `Shift` + `L`

## My config

```json
{
    "terminal.integrated.shell.linux": "/bin/bash",
    "extensions.autoUpdate": false,
    "extensions.autoCheckUpdates": false,
    "security.workspace.trust.startupPrompt": "never",
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.banner": "never",
    "security.workspace.trust.emptyWindow": false,
    "remote.autoForwardPorts": false,
    "window.menuBarVisibility": "classic",
    "[python]": {
        "editor.tabSize": 4,
        "editor.rulers": [80]
      },
    "[r]": {
        "editor.tabSize": 2,
        "editor.rulers": [80]
      },
      "posit.workbench.showWorkbenchFlaskHint": false,
      "posit.workbench.showWorkbenchHint": false,
      "jupyter.interactiveWindow.textEditor.executeSelection": true,
}
```

## My extensions

```json
{
    "recommendations": [
        "charliermarsh.ruff",
        "ms-python.python",
        "ms-toolsai.jupyter",
        "quarto.quarto",
        "rstudio.rstudio-workbench",
        "alefragnani.project-manager",
        "sleistner.vscode-fileutils",
        "mhutchie.git-graph",
        "streetsidesoftware.code-spell-checker"
    ]
}
```
