'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'python-fastapi'
entrypoint = 'app:app'
validate = true
title = 'fastapi-penguins'

[python]
version = "3.11.1"
package-file = "requirements.txt"
package-manager = "pip"
