[project]
name = "databricks-shiny-python-chatbot"
version = "0.1.0"
requires-python = ">=3.12.6"
dependencies = [
    "chatlas[databricks]>=0.7.0",
    "databricks-sdk>=0.52.0",
    "ipykernel>=6.29.5",
    "loguru>=0.7.3",
    "posit-sdk>=0.9.0",
    "shiny>=1.4.0",
]
